import { expect, test, type Page } from '@playwright/test'

test.use({ launchOptions: { args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] } })

const userId = '00000000-0000-4000-8000-000000000123'
const storageKey = 'dompet-santai-notes-v1:' + userId

// Authentication is mocked in the browser: no real account or database writes.
async function signIn(page: Page, id = userId) {
  const user = { id, aud: 'authenticated', role: 'authenticated', email: 'notes@example.com', app_metadata: {}, user_metadata: {}, created_at: '2026-01-01T00:00:00Z' }
  const encode = (value: unknown) => Buffer.from(JSON.stringify(value)).toString('base64url')
  const token = encode({ alg: 'HS256', typ: 'JWT' }) + '.' + encode({
    sub: id, aud: 'authenticated', role: 'authenticated', email: user.email,
    exp: Math.floor(Date.now() / 1000) + 3600, iat: Math.floor(Date.now() / 1000),
  }) + '.' + Buffer.from('test-signature').toString('base64url')
  await page.route('**/auth/v1/**', async route => {
    const url = new URL(route.request().url())
    if (url.pathname.endsWith('/user')) {
      await route.fulfill({ json: user })
    } else if (url.pathname.endsWith('/token')) {
      await route.fulfill({ json: { access_token: token, refresh_token: 'test-refresh-token', token_type: 'bearer', expires_in: 3600, user } })
    } else {
      await route.fulfill({ status: 400, json: { message: 'Unexpected auth request in UI test' } })
    }
  })
  // Prevent server-side verification of the fake test session; client auth requests remain mocked.
  await page.route('http://localhost:3000/**', async route => {
    if (route.request().isNavigationRequest()) {
      const headers = { ...route.request().headers() }
      delete headers.cookie
      await route.continue({ headers })
    } else await route.continue()
  })
  await page.goto('/login')
  await page.waitForFunction(() => (document.querySelector('#__nuxt') as any)?.__vue_app__?.$nuxt?.isHydrating === false)
  await page.getByLabel('Alamat email').fill(user.email)
  await page.getByLabel('Kata sandi', { exact: true }).fill('test-password-123')
  await page.getByRole('button', { name: 'Masuk ke Dompet Santai', exact: true }).click()
  await expect(page.getByTestId('page-title')).toHaveText('Dompet Santai')
}

async function seedExpenseBudgets(page: Page, categories = ['food']) {
  await page.addInitScript(({ id, categories }) => {
    const now = new Date()
    const month = now.getFullYear() + '-' + String(now.getMonth() + 1).padStart(2, '0')
    const key = 'dompet-santai-budgets-v1:' + id
    if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify(categories.map(category => ({ month, category, limit: 1000000 }))))
  }, { id: userId, categories })
}

async function openNote(page: Page) {
  await page.getByRole('button', { name: 'Tambah Catatan', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Tambah Catatan' })
  await expect(dialog).toBeVisible()
  return dialog
}

test('expense saves once, updates the dashboard, survives remount and supports undo', async ({ page }) => {
  await page.addInitScript(() => {
    const date = new Date()
    const month = date.getFullYear() + '-' + String(date.getMonth() + 1).padStart(2, '0')
    const key = 'dompet-santai-budgets-v1:00000000-0000-4000-8000-000000000123'
    if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify([{ month, category: 'food', limit: 180000 }, { month, category: 'transport', limit: 100000 }]))
  })
  await signIn(page)
  const dialog = await openNote(page)
  await expect(dialog.getByLabel('Nominal dalam rupiah')).toBeFocused()
  await dialog.getByLabel('Nominal dalam rupiah').fill('25000')
  await expect(dialog.getByLabel('Nominal dalam rupiah')).toHaveValue('25.000')
  await dialog.getByRole('radio', { name: 'Makan & Minum' }).check()
  await dialog.getByLabel('Bayar dari').selectOption('ewallet')
  await dialog.getByLabel('Keterangan').fill('Makan siang')
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('.note-toast [role=status]')).toHaveText('Catatan tersimpan')
  await expect(page.locator('.summary-card').filter({ hasText: 'Saldo Nyata' })).toContainText(/8\.425\.000/)
  await expect(page.locator('.summary-card').filter({ hasText: 'Uang Aman Dipakai' })).toContainText(/2\.125\.000/)
  await expect(page.locator('.summary-card').filter({ hasText: 'Pengeluaran Hari Ini' })).toContainText(/150\.000/)
  await expect(page.locator('.budget-card').filter({ hasText: 'Makan & Minum' })).toContainText(/155\.000/)
  await expect(page.locator('.saved-note')).toHaveCount(1)
  await expect(page.locator('.saved-note')).toContainText('Makan siang')
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!).length, storageKey)).toBe(1)
  await page.getByRole('button', { name: 'Urungkan', exact: true }).click()
  await expect(page.locator('.saved-note')).toHaveCount(0)
  await expect(page.locator('.summary-card').filter({ hasText: 'Saldo Nyata' })).toContainText(/8\.450\.000/)
  const next = await openNote(page)
  await next.getByLabel('Nominal dalam rupiah').fill('50000')
  await next.getByRole('radio', { name: 'Transportasi' }).check()
  await next.getByRole('button', { name: 'Simpan Catatan' }).click()
  await page.reload()
  await signIn(page)
  await expect(page.getByTestId('page-title')).toBeVisible()
  await expect(page.locator('.saved-note')).toHaveCount(1)
  await expect(page.locator('.summary-card').filter({ hasText: 'Saldo Nyata' })).toContainText(/8\.400\.000/)
})

test('income categories, historical date and validation do not inflate today expenses', async ({ page }) => {
  await seedExpenseBudgets(page, ["food"])
  await signIn(page)
  const dialog = await openNote(page)
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(dialog.getByText('Isi nominal Rp1 sampai')).toBeVisible()
  await dialog.getByLabel('Nominal dalam rupiah').fill('-25000')
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(dialog.getByLabel('Nominal dalam rupiah')).toHaveAttribute('aria-invalid', 'true')
  await dialog.getByLabel('Nominal dalam rupiah').fill('100000')
  await dialog.getByRole('radio', { name: 'Pemasukan', exact: true }).check()
  await expect(dialog.getByRole('radio', { name: 'Makan & Minum' })).toHaveCount(0)
  await dialog.getByRole('radio', { name: 'Gaji', exact: true }).check()
  await dialog.getByLabel('Tanggal').fill('2099-01-01')
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(dialog.getByText('Pilih tanggal yang valid sampai hari ini.')).toBeVisible()
  await dialog.getByLabel('Tanggal').fill('2020-01-01')
  await dialog.getByLabel('Masuk ke').selectOption('bank')
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(page.locator('.summary-card').filter({ hasText: 'Saldo Nyata' })).toContainText(/8\.550\.000/)
  await expect(page.locator('.summary-card').filter({ hasText: 'Pengeluaran Hari Ini' })).toContainText(/125\.000/)
})

test('mobile sheet follows light and dark themes, traps focus and confirms discarded drafts', async ({ page }) => {
  await seedExpenseBudgets(page, ["food"])
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ colorScheme: 'light' })
  await signIn(page)
  const dialog = await openNote(page)
  const light = await dialog.evaluate(el => getComputedStyle(el).backgroundColor)
  await dialog.getByRole('button', { name: 'Gunakan mode gelap' }).click()
  const dark = await dialog.evaluate(el => getComputedStyle(el).backgroundColor)
  expect(dark).not.toBe(light)
  const bounds = await dialog.boundingBox()
  expect(bounds!.width).toBeLessThanOrEqual(390)
  expect(Math.abs(bounds!.y + bounds!.height - 844)).toBeLessThanOrEqual(2)
  await page.screenshot({ animations: 'disabled', path: 'test-results/add-note-mobile-dark.png' })
  await dialog.getByRole('button', { name: 'Gunakan mode terang' }).click()
  await page.screenshot({ animations: 'disabled', path: 'test-results/add-note-mobile-light.png' })
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).focus()
  await page.keyboard.press('Tab')
  expect(await page.evaluate(() => !!document.activeElement?.closest('dialog'))).toBe(true)
  await dialog.getByLabel('Nominal dalam rupiah').fill('12000')
  await page.keyboard.press('Escape')
  await expect(dialog.getByText('Isian belum disimpan. Tutup dan buang isian?')).toBeVisible()
  await dialog.getByRole('button', { name: 'Lanjut mengisi' }).click()
  await expect(dialog.getByLabel('Nominal dalam rupiah')).toHaveValue('12.000')
  await dialog.getByRole('button', { name: 'Tutup tambah catatan' }).click()
  await dialog.getByRole('button', { name: 'Buang isian' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Tambah Catatan', exact: true })).toBeFocused()
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
})

test('storage failures keep the form open and never report a successful save', async ({ page }) => {
  await seedExpenseBudgets(page, ["bills"])
  await signIn(page)
  const dialog = await openNote(page)
  await dialog.getByLabel('Nominal dalam rupiah').fill('25000')
  await dialog.getByRole('radio', { name: 'Tagihan' }).check()
  await page.evaluate(() => {
    Storage.prototype.setItem = () => { throw new DOMException('Full', 'QuotaExceededError') }
  })
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(dialog).toBeVisible()
  await expect(dialog.getByText('Perubahan belum tersimpan.', { exact: false })).toBeVisible()
  await expect(page.locator('.saved-note')).toHaveCount(0)
  await expect(page.locator('.note-toast [role=status]')).toHaveCount(0)
})

test('desktop modal matches both themes without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.emulateMedia({ colorScheme: 'light' })
  await signIn(page)
  const dialog = await openNote(page)
  await page.screenshot({ animations: 'disabled', path: 'test-results/add-note-desktop-light.png' })
  await dialog.getByRole('button', { name: 'Gunakan mode gelap' }).click()
  await page.screenshot({ animations: 'disabled', path: 'test-results/add-note-desktop-dark.png' })
  expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})


test('saved notes are isolated between accounts on the same browser', async ({ page }) => {
  await seedExpenseBudgets(page, ["food"])
  await signIn(page)
  const dialog = await openNote(page)
  await dialog.getByLabel('Nominal dalam rupiah').fill('15000')
  await dialog.getByRole('radio', { name: 'Makan & Minum' }).check()
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(page.locator('.saved-note')).toHaveCount(1)
  await signIn(page, '00000000-0000-4000-8000-000000000456')
  await expect(page.locator('.saved-note')).toHaveCount(0)
  await expect(page.locator('.summary-card').filter({ hasText: 'Saldo Nyata' })).toContainText(/8\.450\.000/)
  await signIn(page)
  await expect(page.locator('.saved-note')).toHaveCount(1)
})

test('unreadable saved data is reported and not overwritten', async ({ page }) => {
  await page.addInitScript(key => localStorage.setItem(key, 'invalid-json'), storageKey)
  await signIn(page)
  await expect(page.getByRole('alert')).toContainText('Catatan di browser belum bisa dibaca')
  const dialog = await openNote(page)
  await expect(dialog.getByRole('button', { name: 'Simpan Catatan' })).toBeDisabled()
  expect(await page.evaluate(key => localStorage.getItem(key), storageKey)).toBe('invalid-json')
})

test('wallet balances block unaffordable expenses, permit exact balances and never restrict income', async ({ page }) => {
  await seedExpenseBudgets(page, ["food"])
  await page.setViewportSize({ width: 390, height: 844 })
  await signIn(page)
  const dialog = await openNote(page)
  const account = dialog.getByLabel('Bayar dari')
  const save = dialog.getByRole('button', { name: 'Simpan Catatan' })
  await expect(account.locator('option[value=cash]')).toContainText(/450\.000/)
  await expect(account.locator('option[value=bank]')).toContainText(/6\.500\.000/)
  await expect(account.locator('option[value=ewallet]')).toContainText(/1\.500\.000/)
  await dialog.getByLabel('Nominal dalam rupiah').fill('450001')
  await dialog.getByRole('radio', { name: 'Makan & Minum' }).check()
  await expect(save).toBeDisabled()
  await expect(dialog.getByRole('alert')).toContainText('Saldo Tunai tidak cukup')
  await expect(dialog.getByRole('alert')).toContainText(/Kurang Rp\s?1\./)
  // Enter/programmatic submission cannot bypass the disabled button.
  await dialog.locator('form').evaluate(form => (form as HTMLFormElement).requestSubmit())
  await expect(page.locator('.saved-note')).toHaveCount(0)
  await account.selectOption('bank')
  await expect(save).toBeEnabled()
  await expect(dialog.locator('.balance-preview')).toContainText(/6\.049\.999/)
  await account.selectOption('cash')
  await expect(save).toBeDisabled()
  await dialog.getByRole('button', { name: 'Gunakan mode gelap' }).click()
  await page.screenshot({ animations: 'disabled', path: 'test-results/insufficient-wallet-mobile-dark.png' })
  await dialog.getByLabel('Nominal dalam rupiah').fill('450000')
  await expect(save).toBeEnabled()
  await expect(dialog.locator('.balance-preview')).toContainText(/Rp\s?0/)
  await save.click()

  const next = await openNote(page)
  await expect(next.getByLabel('Bayar dari').locator('option[value=cash]')).toContainText(/Rp\s?0$/)
  await next.getByLabel('Nominal dalam rupiah').fill('1')
  await expect(next.getByRole('button', { name: 'Simpan Catatan' })).toBeDisabled()
  await next.getByRole('radio', { name: 'Pemasukan', exact: true }).check()
  await next.getByRole('radio', { name: 'Gaji', exact: true }).check()
  await next.getByLabel('Nominal dalam rupiah').fill('100000')
  await expect(next.getByRole('button', { name: 'Simpan Catatan' })).toBeEnabled()
  await next.getByRole('button', { name: 'Simpan Catatan' }).click()
  await page.getByRole('button', { name: 'Urungkan', exact: true }).click()
  await page.reload()
  await signIn(page)
  const reloaded = await openNote(page)
  await expect(reloaded.getByLabel('Bayar dari').locator('option[value=cash]')).toContainText(/Rp\s?0$/)
  await expect(reloaded.getByLabel('Bayar dari').locator('option[value=bank]')).toContainText(/6\.500\.000/)
})

test('saving checks the latest stored wallet balance even before a storage event arrives', async ({ page }) => {
  await seedExpenseBudgets(page, ["food"])
  await signIn(page)
  const dialog = await openNote(page)
  await dialog.getByLabel('Nominal dalam rupiah').fill('50000')
  await dialog.getByRole('radio', { name: 'Makan & Minum' }).check()
  // Simulate another write after this form has read its initial balance.
  await page.evaluate(key => {
    const now = new Date()
    const date = [now.getFullYear(), String(now.getMonth() + 1).padStart(2, '0'), String(now.getDate()).padStart(2, '0')].join('-')
    localStorage.setItem(key, JSON.stringify([{
      id: 'other-tab', type: 'expense', amount: 440000, account: 'cash', category: 'food',
      date, description: 'Dari tab lain', createdAt: now.toISOString(),
    }]))
  }, storageKey)
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Simpan Catatan' })).toBeDisabled()
  await expect(dialog.locator('#note-funds-error')).toContainText(/40\.000/)
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!).length, storageKey)).toBe(1)
})

async function receiptPhoto(page: Page, name = 'struk-belanja.png') {
  const dataUrl = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 600
    canvas.height = 1000
    const context = canvas.getContext('2d')!
    context.fillStyle = '#fff'
    context.fillRect(0, 0, 600, 1000)
    context.fillStyle = '#202824'
    context.font = 'bold 32px sans-serif'
    context.fillText('STRUK CONTOH', 50, 100)
    context.font = '24px sans-serif'
    context.fillText('Warung Santai', 50, 150)
    context.fillText('Makan siang        Rp25.000', 50, 300)
    context.fillText('TOTAL              Rp25.000', 50, 440)
    context.fillText('Terima kasih!', 50, 600)
    return canvas.toDataURL('image/png')
  })
  return { name, mimeType: 'image/png', buffer: Buffer.from(dataUrl.split(',')[1]!, 'base64') }
}

test('optional receipt previews automatically, opens larger and persists with the saved note', async ({ page }) => {
  await seedExpenseBudgets(page, ["food"])
  await signIn(page)
  const dialog = await openNote(page)
  await dialog.getByLabel('Nominal dalam rupiah').fill('25000')
  await dialog.getByRole('radio', { name: 'Makan & Minum' }).check()
  await dialog.getByLabel('Pilih foto struk', { exact: true }).setInputFiles(await receiptPhoto(page))
  const preview = dialog.getByAltText('Pratinjau foto struk')
  await expect(preview).toBeVisible()
  await expect(preview).toHaveJSProperty('naturalWidth', 600)
  await dialog.getByRole('button', { name: 'Lihat foto struk lebih besar' }).click()
  const viewer = page.getByRole('dialog', { name: 'Foto struk', exact: true })
  await expect(viewer).toBeVisible()
  await expect(viewer.getByAltText('Foto struk tersimpan')).toHaveJSProperty('naturalWidth', 600)
  await viewer.getByRole('button', { name: 'Perbesar', exact: true }).click()
  await expect(viewer.getByRole('button', { name: 'Sesuaikan layar' })).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('Escape')
  await expect(viewer).not.toBeVisible()
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'Lihat foto struk lebih besar' })).toBeFocused()
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(page.locator('.saved-note').getByRole('button', { name: 'Lihat struk' })).toBeVisible()
  await page.reload()
  await signIn(page)
  await page.locator('.saved-note').getByRole('button', { name: 'Lihat struk' }).click()
  const savedViewer = page.getByRole('dialog', { name: 'Foto struk', exact: true })
  await expect(savedViewer.getByAltText('Foto struk tersimpan')).toHaveJSProperty('naturalWidth', 600)
  await savedViewer.getByRole('button', { name: 'Tutup foto struk' }).click()
  expect(await page.evaluate(() => document.body.style.overflow)).not.toBe('hidden')
})

test('receipt selection supports upload, replacement, removal, validation and unsaved-photo confirmation', async ({ page }) => {
  await seedExpenseBudgets(page, ["food"])
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ colorScheme: 'light' })
  await signIn(page)
  const dialog = await openNote(page)
  await dialog.getByLabel('Pilih foto struk', { exact: true }).setInputFiles(await receiptPhoto(page))
  await expect(dialog.getByAltText('Pratinjau foto struk')).toBeVisible()
  await page.screenshot({ animations: 'disabled', path: 'test-results/receipt-mobile-light.png' })
  await dialog.getByRole('button', { name: 'Gunakan mode gelap' }).click()
  await dialog.getByAltText('Pratinjau foto struk').scrollIntoViewIfNeeded()
  await page.screenshot({ animations: 'disabled', path: 'test-results/receipt-mobile-dark.png' })
  await dialog.getByRole('button', { name: 'Tutup tambah catatan' }).click()
  await expect(dialog.getByText('Isian belum disimpan. Tutup dan buang isian?')).toBeVisible()
  await dialog.getByRole('button', { name: 'Lanjut mengisi' }).click()

  const input = dialog.getByLabel('Pilih foto struk', { exact: true })
  await input.setInputFiles({ name: 'text.txt', mimeType: 'text/plain', buffer: Buffer.from('not a photo') })
  await expect(dialog.getByRole('alert')).toContainText('Gunakan foto JPG, PNG, atau WebP')
  await expect(dialog.getByAltText('Pratinjau foto struk')).toBeVisible()
  await input.setInputFiles({ name: 'broken.jpg', mimeType: 'image/jpeg', buffer: Buffer.from('not a real jpeg') })
  await expect(dialog.getByRole('alert')).toContainText('Foto tidak bisa dibaca')
  await input.setInputFiles({ name: 'large.jpg', mimeType: 'image/jpeg', buffer: Buffer.alloc(10 * 1024 * 1024 + 1) })
  await expect(dialog.getByRole('alert')).toContainText('Ukuran foto maksimal 10 MB')
  await input.setInputFiles(await receiptPhoto(page, 'struk-pengganti.png'))
  await expect(dialog.locator('.receipt-preview__caption')).toContainText('struk-pengganti.png')
  await dialog.getByRole('button', { name: 'Hapus foto' }).click()
  await expect(dialog.getByAltText('Pratinjau foto struk')).toHaveCount(0)
  await dialog.getByLabel('Nominal dalam rupiah').fill('10000')
  await dialog.getByRole('radio', { name: 'Makan & Minum' }).check()
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!)[0].receipt, storageKey)).toBeUndefined()
  await expect(page.locator('.saved-note').getByRole('button', { name: 'Lihat struk' })).toHaveCount(0)
})

test('failed photo storage preserves the draft and allows saving again without the attachment', async ({ page }) => {
  await seedExpenseBudgets(page, ["food"])
  await signIn(page)
  const dialog = await openNote(page)
  await dialog.getByLabel('Nominal dalam rupiah').fill('10000')
  await dialog.getByRole('radio', { name: 'Makan & Minum' }).check()
  await dialog.getByLabel('Pilih foto struk', { exact: true }).setInputFiles(await receiptPhoto(page))
  await expect(dialog.getByAltText('Pratinjau foto struk')).toBeVisible()
  await page.evaluate(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function(key, value) {
      if (key.startsWith('dompet-santai-notes-') && value.includes('data:image/')) throw new DOMException('Full', 'QuotaExceededError')
      return original.call(this, key, value)
    }
  })
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(dialog.getByRole('alert')).toContainText('Perubahan belum tersimpan')
  await expect(dialog.getByAltText('Pratinjau foto struk')).toBeVisible()
  await expect(page.locator('.saved-note')).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Hapus foto' }).click()
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('.saved-note')).toHaveCount(1)
})

test.describe('live receipt camera', () => {

  test('opens a real video stream, captures a frame and stops the camera after capture or cancellation', async ({ page }) => {
    await seedExpenseBudgets(page, ['food'])
    await page.setViewportSize({ width: 390, height: 844 })
    await page.addInitScript(() => {
      const original = navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices)
      ;(window as any).__cameraStreams = []
      ;(window as any).__cameraRequests = []
      navigator.mediaDevices.getUserMedia = async constraints => {
        ;(window as any).__cameraRequests.push(constraints)
        const stream = await original(constraints)
        ;(window as any).__cameraStreams.push(stream)
        return stream
      }
    })
    let filePickerOpened = false
    page.on('filechooser', () => { filePickerOpened = true })
    await signIn(page)
    const dialog = await openNote(page)
    await dialog.getByLabel('Nominal dalam rupiah').fill('25000')
    await dialog.getByRole('radio', { name: 'Makan & Minum' }).check()
    await dialog.getByRole('button', { name: 'Ambil foto', exact: true }).click()
    const camera = page.getByRole('dialog', { name: 'Kamera struk', exact: true })
    await expect(camera).toBeVisible()
    await expect(camera.getByRole('button', { name: 'Jepret foto' })).toBeEnabled()
    expect(await camera.locator('video').evaluate(video => (video as HTMLVideoElement).videoWidth)).toBeGreaterThan(0)
    expect(await page.evaluate(() => (window as any).__cameraRequests[0])).toMatchObject({
      audio: false, video: { facingMode: { ideal: 'environment' } },
    })
    expect(filePickerOpened).toBe(false)
    await page.screenshot({ animations: 'disabled', path: 'test-results/receipt-live-camera-mobile.png' })
    await camera.getByRole('button', { name: 'Jepret foto' }).click()
    await expect(camera).not.toBeVisible()
    await expect(dialog.getByAltText('Pratinjau foto struk')).toBeVisible()
    expect(await page.evaluate(() => (window as any).__cameraStreams.every((stream: MediaStream) => stream.getTracks().every(track => track.readyState === 'ended')))).toBe(true)
    await dialog.getByRole('button', { name: 'Ambil foto', exact: true }).click()
    await expect(camera.getByRole('button', { name: 'Jepret foto' })).toBeEnabled()
    await page.keyboard.press('Escape')
    await expect(camera).not.toBeVisible()
    await expect(dialog).toBeVisible()
    await expect(dialog.getByAltText('Pratinjau foto struk')).toBeVisible()
    expect(await page.evaluate(() => (window as any).__cameraStreams.every((stream: MediaStream) => stream.getTracks().every(track => track.readyState === 'ended')))).toBe(true)
    await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
    await expect(page.locator('.saved-note').getByRole('button', { name: 'Lihat struk' })).toBeVisible()
  })

  for (const [errorName, message] of [
    ['NotAllowedError', 'Akses kamera ditolak'],
    ['NotFoundError', 'Kamera tidak ditemukan'],
    ['NotReadableError', 'Kamera sedang digunakan'],
  ]) {
    test('explains ' + errorName + ' and keeps the existing receipt intact', async ({ page }) => {
      await signIn(page)
      const dialog = await openNote(page)
      await dialog.getByLabel('Pilih foto struk', { exact: true }).setInputFiles(await receiptPhoto(page))
      await expect(dialog.getByAltText('Pratinjau foto struk')).toBeVisible()
      await page.evaluate(name => {
        navigator.mediaDevices.getUserMedia = async () => { throw new DOMException('Camera test', name) }
      }, errorName)
      await dialog.getByRole('button', { name: 'Ambil foto', exact: true }).click()
      const camera = page.getByRole('dialog', { name: 'Kamera struk', exact: true })
      await expect(camera.getByRole('alert')).toContainText(message!)
      await expect(camera.getByRole('button', { name: 'Jepret foto' })).toBeDisabled()
      await expect(camera.getByRole('button', { name: 'Pilih dari galeri' })).toBeVisible()
      await camera.getByRole('button', { name: 'Tutup kamera' }).click()
      await expect(dialog.getByAltText('Pratinjau foto struk')).toBeVisible()
      expect(await page.evaluate(() => document.body.style.overflow)).toBe('hidden')
    })
  }

  test('stops a late permission result after the camera dialog has already closed', async ({ page }) => {
    await signIn(page)
    const dialog = await openNote(page)
    await page.evaluate(() => {
      navigator.mediaDevices.getUserMedia = () => new Promise(resolve => {
        ;(window as any).__resolveCamera = () => {
          const canvas = document.createElement('canvas')
          canvas.width = 320
          canvas.height = 240
          const stream = canvas.captureStream()
          ;(window as any).__lateCamera = stream
          resolve(stream)
        }
      })
    })
    await dialog.getByRole('button', { name: 'Ambil foto', exact: true }).click()
    const camera = page.getByRole('dialog', { name: 'Kamera struk', exact: true })
    await expect(camera.getByRole('status')).toContainText('Membuka kamera')
    await camera.getByRole('button', { name: 'Tutup kamera' }).click()
    await page.evaluate(() => (window as any).__resolveCamera())
    await expect.poll(() => page.evaluate(() => (window as any).__lateCamera.getTracks().every((track: MediaStreamTrack) => track.readyState === 'ended'))).toBe(true)
    await expect(camera).not.toBeVisible()
    await expect(dialog).toBeVisible()
    await expect(dialog.getByAltText('Pratinjau foto struk')).toHaveCount(0)
  })
})


for (const width of [1440, 390]) {
  test('expense budget requirement blocks missing budgets and permits income at width ' + width, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await signIn(page)
    await page.addStyleTag({ content: '#nuxt-devtools-container { display: none !important; }' })
    const dialog = await openNote(page)
    const save = dialog.getByRole('button', { name: 'Simpan Catatan' })
    await expect(dialog.locator('#note-budget-error')).toContainText('Belum ada anggaran')
    await expect(save).toBeDisabled()
    await dialog.getByLabel('Nominal dalam rupiah').fill('25000')
    await dialog.getByRole('radio', { name: 'Makan & Minum' }).check()
    await dialog.locator('form').evaluate(form => (form as HTMLFormElement).requestSubmit())
    expect(await page.evaluate(key => localStorage.getItem(key), storageKey)).toBeNull()
    await expect(dialog.getByLabel('Nominal dalam rupiah')).toHaveValue('25.000')

    await dialog.getByRole('radio', { name: 'Pemasukan', exact: true }).check()
    await dialog.getByRole('radio', { name: 'Gaji', exact: true }).check()
    await expect(dialog.locator('#note-budget-error')).toHaveCount(0)
    await save.click()
    await expect(dialog).not.toBeVisible()
    expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!)[0].type, storageKey)).toBe('income')

    await openBudgets(page)
    await createBudget(page, 'food', '100000')
    await page.getByRole('button', { name: 'Lihat anggaran Makan & Minum' }).click()
    await page.getByRole('button', { name: 'Catat Pengeluaran', exact: true }).click()
    await dialog.getByLabel('Nominal dalam rupiah').fill('25000')
    await expect(save).toBeEnabled()
    await save.click()
    await expect(dialog).not.toBeVisible()
    await expect(page.locator('.detail-card')).toContainText('75.000')
    expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!).map((note: any) => note.type), storageKey)).toEqual(['income', 'expense'])
  })
}

test('expense budget requirement follows category, transaction month and account', async ({ page }) => {
  await seedExpenseBudgets(page)
  await signIn(page)
  let dialog = await openNote(page)
  const save = dialog.getByRole('button', { name: 'Simpan Catatan' })
  await dialog.getByLabel('Nominal dalam rupiah').fill('25000')
  await dialog.getByRole('radio', { name: 'Transportasi' }).check()
  await expect(save).toBeDisabled()
  await expect(dialog.locator('#note-budget-error')).toContainText('Kategori ini belum')
  await dialog.getByRole('radio', { name: 'Makan & Minum' }).check()
  await expect(save).toBeEnabled()
  const today = await dialog.getByLabel('Tanggal').inputValue()
  await dialog.getByLabel('Tanggal').fill('2020-01-01')
  await expect(save).toBeDisabled()
  await expect(dialog.locator('#note-budget-error')).toContainText('Belum ada anggaran')
  await dialog.getByLabel('Tanggal').fill(today)
  await expect(save).toBeEnabled()
  await dialog.getByRole('button', { name: 'Tutup tambah catatan' }).click()
  await dialog.getByRole('button', { name: 'Buang isian' }).click()
  await signIn(page, '00000000-0000-4000-8000-000000000456')
  dialog = await openNote(page)
  await expect(dialog.getByRole('button', { name: 'Simpan Catatan' })).toBeDisabled()
  await expect(dialog.locator('#note-budget-error')).toContainText('Belum ada anggaran')
})

test('expense budget requirement rereads storage and preserves drafts when budgets disappear or become unreadable', async ({ page }) => {
  await seedExpenseBudgets(page)
  await signIn(page)
  const dialog = await openNote(page)
  const save = dialog.getByRole('button', { name: 'Simpan Catatan' })
  await dialog.getByLabel('Nominal dalam rupiah').fill('25000')
  await dialog.getByRole('radio', { name: 'Makan & Minum' }).check()
  const budgetKey = 'dompet-santai-budgets-v1:' + userId
  const original = await page.evaluate(key => localStorage.getItem(key)!, budgetKey)
  for (const raw of ['[]', 'invalid-json']) {
    // No storage event: the form still has the initial budget, so persistence must recheck.
    await page.evaluate(({ key, raw }) => localStorage.setItem(key, raw), { key: budgetKey, raw })
    await expect(save).toBeEnabled()
    await save.click()
    await expect(dialog.locator('.save-error')).toContainText(raw === '[]' ? 'Belum ada anggaran' : 'Anggaran belum bisa dibaca')
    await expect(dialog.getByLabel('Nominal dalam rupiah')).toHaveValue('25.000')
    expect(await page.evaluate(key => localStorage.getItem(key), storageKey)).toBeNull()
    expect(await page.evaluate(key => localStorage.getItem(key), budgetKey)).toBe(raw)
    await page.evaluate(({ key, raw }) => localStorage.setItem(key, raw), { key: budgetKey, raw: original })
  }
  await save.click()
  await expect(dialog).not.toBeVisible()
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!).length, storageKey)).toBe(1)
})

test('expense budget requirement handles unreadable budgets without blocking income or allowing conversion to expense', async ({ page }) => {
  const budgetKey = 'dompet-santai-budgets-v1:' + userId
  await page.addInitScript(key => localStorage.setItem(key, 'invalid-json'), budgetKey)
  await signIn(page)
  const dialog = await openNote(page)
  await expect(dialog.locator('#note-budget-error')).toContainText('Anggaran di browser belum bisa dibaca')
  await expect(dialog.getByRole('button', { name: 'Simpan Catatan' })).toBeDisabled()
  await dialog.getByRole('radio', { name: 'Pemasukan', exact: true }).check()
  await dialog.getByRole('radio', { name: 'Gaji', exact: true }).check()
  await dialog.getByLabel('Nominal dalam rupiah').fill('25000')
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await page.getByRole('button', { name: 'Riwayat', exact: true }).click()
  await page.locator('.history-row').click()
  await page.getByRole('button', { name: 'Ubah Catatan', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Ubah Catatan', exact: true })
  await editor.getByRole('radio', { name: 'Pengeluaran', exact: true }).check()
  await editor.getByRole('radio', { name: 'Makan & Minum' }).check()
  await expect(editor.getByRole('button', { name: 'Simpan Perubahan' })).toBeDisabled()
  await editor.locator('form').evaluate(form => (form as HTMLFormElement).requestSubmit())
  expect(await page.evaluate(key => JSON.parse(localStorage.getItem(key)!)[0].type, storageKey)).toBe('income')
  expect(await page.evaluate(key => localStorage.getItem(key), budgetKey)).toBe('invalid-json')
})

async function openBudgets(page: Page) {
  await page.getByRole('button', { name: 'Anggaran', exact: true }).click()
  await expect(page).toHaveURL(/\/anggaran$/)
  await expect(page.locator('.budget-overview')).toBeVisible()
}
async function createBudget(page: Page, category = 'food', limit = '20000') {
  await page.getByRole('button', { name: 'Buat Anggaran', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Buat Anggaran', exact: true })
  await expect(editor).toBeVisible()
  await editor.getByLabel('Kategori', { exact: true }).selectOption(category)
  await editor.getByLabel('Batas anggaran (Rp)', { exact: true }).fill(limit)
  await editor.getByRole('button', { name: 'Simpan Anggaran' }).click()
  await expect(editor).not.toBeVisible()
}
test('budgets create, reject duplicates, edit and follow expense saving and undo', async ({ page }) => {
  test.setTimeout(60000)
  await signIn(page)
  await openBudgets(page)
  await expect(page.getByText('Mulai atur anggaranmu')).toBeVisible()
  await createBudget(page)
  await expect(page.locator('.category-card')).toContainText('20.000')
  await page.getByRole('button', { name: 'Buat Anggaran', exact: true }).click()
  let editor = page.getByRole('dialog', { name: 'Buat Anggaran', exact: true })
  await editor.getByLabel('Kategori', { exact: true }).selectOption('food')
  await expect(editor.getByRole('button', { name: 'Simpan Anggaran' })).toBeDisabled()
  await editor.getByRole('button', { name: 'Batal', exact: true }).click()
  await editor.getByRole('button', { name: 'Buang isian' }).click()
  await page.getByRole('button', { name: 'Lihat anggaran Makan & Minum' }).click()
  await page.getByRole('button', { name: 'Catat Pengeluaran', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Tambah Catatan' })
  await expect(dialog.getByRole('radio', { name: 'Makan & Minum' })).toBeChecked()
  await dialog.getByLabel('Nominal dalam rupiah').fill('25000')
  await expect(dialog.locator('.budget-warning')).toContainText('5.000')
  await expect(dialog.getByRole('button', { name: 'Simpan Catatan' })).toBeEnabled()
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(page.locator('.detail-card .status')).toHaveText('Terlewati')
  await expect(page.locator('.transactions li')).toHaveCount(1)
  await page.getByRole('button', { name: 'Urungkan', exact: true }).click()
  await expect(page.locator('.detail-card .status')).toHaveText('Masih aman')
  await expect(page.locator('.transactions li')).toHaveCount(0)
  await page.getByRole('button', { name: 'Ubah Anggaran', exact: true }).click()
  editor = page.getByRole('dialog', { name: 'Ubah Anggaran', exact: true })
  await editor.getByLabel('Batas anggaran (Rp)', { exact: true }).fill('50000')
  await editor.getByRole('button', { name: 'Simpan Anggaran' }).click()
  await expect(page.locator('.detail-card')).toContainText('50.000')
  await page.getByRole('button', { name: 'Beranda', exact: true }).click()
  await expect(page.locator('.budget-card')).toContainText('50.000')
  await openBudgets(page)
  await page.getByLabel('Periode', { exact: true }).fill('2020-01')
  await expect(page.getByText('Mulai atur anggaranmu')).toBeVisible()
  await createBudget(page, 'food', '100000')
  await page.getByRole('button', { name: 'Lihat anggaran Makan & Minum' }).click()
  await page.getByRole('button', { name: 'Catat Pengeluaran', exact: true }).click()
  await expect(dialog.getByLabel('Tanggal')).toHaveValue('2020-01-01')
  await dialog.getByLabel('Nominal dalam rupiah').fill('30000')
  await dialog.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(page.locator('.detail-card')).toContainText('70.000')
  await page.getByLabel('Periode', { exact: true }).fill('2099-01')
  await createBudget(page, 'transport')
  await page.getByRole('button', { name: 'Lihat anggaran Transportasi' }).click()
  await expect(page.getByRole('button', { name: 'Catat Pengeluaran', exact: true })).toBeDisabled()
  await page.reload()
  await signIn(page)
  await openBudgets(page)
  await expect(page.locator('.category-card')).toContainText('50.000')
  await signIn(page, '00000000-0000-4000-8000-000000000456')
  await openBudgets(page)
  await expect(page.getByText('Mulai atur anggaranmu')).toBeVisible()
})
test('budgets show legacy unbudgeted spending and preserve draft after failed storage', async ({ page }) => {
  await page.addInitScript(key => {
    const now = new Date()
    const date = [now.getFullYear(), String(now.getMonth() + 1).padStart(2, '0'), String(now.getDate()).padStart(2, '0')].join('-')
    localStorage.setItem(key, JSON.stringify([{ id: 'legacy', type: 'expense', amount: 10000, category: 'bills', account: 'cash', date, description: '', createdAt: now.toISOString() }]))
  }, storageKey)
  await signIn(page)
  await openBudgets(page)
  await expect(page.locator('.unbudgeted')).toContainText('10.000')
  await expect(page.locator('.summary-metrics')).not.toContainText('10.000')
  await page.getByRole('button', { name: 'Atur Anggaran Tagihan' }).click()
  const editor = page.getByRole('dialog', { name: 'Buat Anggaran', exact: true })
  await expect(editor.getByLabel('Kategori', { exact: true })).toHaveValue('bills')
  await editor.getByLabel('Batas anggaran (Rp)', { exact: true }).fill('40000')
  await page.evaluate(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function(key, value) {
      if (key.startsWith('dompet-santai-budgets')) throw new DOMException('Full', 'QuotaExceededError')
      return original.call(this, key, value)
    }
  })
  await editor.getByRole('button', { name: 'Simpan Anggaran' }).click()
  await expect(editor.getByRole('alert')).toContainText('belum tersimpan')
  await expect(editor.getByLabel('Batas anggaran (Rp)', { exact: true })).toHaveValue('40000')
})
test('budgets follow desktop and mobile themes without horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.emulateMedia({ colorScheme: 'light' })
  await signIn(page)
  // The development toolbar overlaps the mobile navigation; it is absent in production.
  await page.addStyleTag({ content: '#nuxt-devtools-container { display: none !important; }' })
  await openBudgets(page)
  await createBudget(page, 'food', '300000')
  await createBudget(page, 'transport', '500000')
  await createBudget(page, 'shopping', '1000000')
  await page.screenshot({ animations: 'disabled', path: 'test-results/budgets-desktop-light.png', fullPage: true })
  const light = await page.locator('.category-card').first().evaluate(el => getComputedStyle(el).backgroundColor)
  await page.getByRole('button', { name: 'Gunakan mode gelap' }).click()
  const dark = await page.locator('.category-card').first().evaluate(el => getComputedStyle(el).backgroundColor)
  expect(dark).not.toBe(light)
  await page.screenshot({ animations: 'disabled', path: 'test-results/budgets-desktop-dark.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ animations: 'disabled', path: 'test-results/budgets-mobile-dark.png', fullPage: true })
  await page.getByRole('button', { name: 'Gunakan mode terang' }).click()
  await page.screenshot({ animations: 'disabled', path: 'test-results/budgets-mobile-light.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Beranda', exact: true }).click()
  await openBudgets(page)
  await page.getByRole('button', { name: 'Buat Anggaran', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Buat Anggaran', exact: true })
  const bounds = await editor.boundingBox()
  expect(Math.abs(bounds!.width - 390)).toBeLessThanOrEqual(2)
  expect(Math.abs(bounds!.y + bounds!.height - 844)).toBeLessThanOrEqual(2)
  await page.screenshot({ animations: 'disabled', path: 'test-results/budget-editor-mobile.png' })
})


test('custom category connects budgets and notes, survives reload and stays isolated per account', async ({ page }) => {
  test.setTimeout(60000)
  await signIn(page)
  await openBudgets(page)
  await page.getByRole('button', { name: 'Buat Anggaran', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Buat Anggaran', exact: true })
  await editor.getByRole('button', { name: 'Tambah Kategori', exact: true }).click()
  await editor.getByLabel('Nama kategori', { exact: true }).fill('Pendidikan')
  await editor.getByLabel('Ikon kategori', { exact: true }).selectOption('school')
  await expect(editor.getByRole('button', { name: 'Simpan Anggaran' })).toBeDisabled()
  await editor.getByRole('button', { name: 'Simpan Kategori', exact: true }).click()
  await expect(editor.locator('#budget-category option:checked')).toHaveText('Pendidikan')
  await editor.getByLabel('Batas anggaran (Rp)', { exact: true }).fill('100000')
  await editor.getByRole('button', { name: 'Simpan Anggaran' }).click()
  await page.getByRole('button', { name: 'Lihat anggaran Pendidikan' }).click()
  await page.getByRole('button', { name: 'Catat Pengeluaran', exact: true }).click()
  const note = page.getByRole('dialog', { name: 'Tambah Catatan' })
  await expect(note.getByRole('radio', { name: 'Pendidikan', exact: true })).toBeChecked()
  await note.getByLabel('Nominal dalam rupiah').fill('25000')
  await note.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(page.locator('.detail-card')).toContainText('75.000')
  await page.reload()
  await signIn(page)
  await expect(page.locator('.saved-note')).toContainText('Pendidikan')
  await expect(page.locator('.budget-card')).toContainText('75.000')
  await openBudgets(page)
  await page.getByRole('button', { name: 'Lihat anggaran Pendidikan' }).click()
  await expect(page.locator('.transactions li')).toContainText('25.000')
  await signIn(page, '00000000-0000-4000-8000-000000000456')
  const other = await openNote(page)
  await expect(other.getByRole('radio', { name: 'Pendidikan', exact: true })).toHaveCount(0)
})
test('custom category creation validates names, separates income and preserves the existing note draft', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await signIn(page)
  await page.addStyleTag({ content: '#nuxt-devtools-container { display: none !important; }' })
  const note = await openNote(page)
  await note.getByLabel('Nominal dalam rupiah').fill('50000')
  await note.getByLabel('Keterangan').fill('Isian tetap ada')
  await note.getByRole('button', { name: 'Tambah Kategori', exact: true }).click()
  await note.getByRole('button', { name: 'Simpan Kategori', exact: true }).click()
  await expect(note.locator('.category-error')).toContainText('1 sampai 32')
  await note.getByLabel('Nama kategori', { exact: true }).fill('  makan & MINUM ')
  await note.getByRole('button', { name: 'Simpan Kategori', exact: true }).click()
  await expect(note.locator('.category-error')).toContainText('sudah digunakan')
  await note.getByLabel('Nama kategori', { exact: true }).fill('PerawatanHewanDanKebutuhanHarian')
  await note.getByLabel('Ikon kategori', { exact: true }).selectOption('pets')
  await page.screenshot({ path: 'test-results/custom-category-mobile-light.png' })
  await note.getByRole('button', { name: 'Gunakan mode gelap' }).click()
  await page.screenshot({ path: 'test-results/custom-category-mobile-dark.png' })
  expect(await note.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await note.getByRole('button', { name: 'Simpan Kategori', exact: true }).click()
  await expect(note.getByRole('radio', { name: 'PerawatanHewanDanKebutuhanHarian', exact: true })).toBeChecked()
  await expect(note.getByRole('button', { name: 'Simpan Catatan' })).toBeDisabled()
  await expect(note.locator('#note-budget-error')).toBeVisible()
  expect(await note.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await expect(note.getByLabel('Nominal dalam rupiah')).toHaveValue('50.000')
  await expect(note.getByLabel('Keterangan')).toHaveValue('Isian tetap ada')
  await note.getByRole('radio', { name: 'Pemasukan', exact: true }).check()
  await expect(note.getByRole('radio', { name: 'PerawatanHewanDanKebutuhanHarian', exact: true })).toHaveCount(0)
  await note.getByRole('button', { name: 'Tambah Kategori', exact: true }).click()
  await note.getByLabel('Nama kategori', { exact: true }).fill('Royalti')
  await note.getByLabel('Nama kategori', { exact: true }).press('Enter')
  await expect(note).toBeVisible()
  await expect(note.getByRole('radio', { name: 'Royalti', exact: true })).toBeChecked()
  await note.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(page.locator('.saved-note')).toContainText('Royalti')
})
test('custom category storage failures retain input and unsaved category closes with confirmation', async ({ page }) => {
  await signIn(page)
  const note = await openNote(page)
  await note.getByRole('button', { name: 'Tambah Kategori', exact: true }).click()
  await note.getByLabel('Nama kategori', { exact: true }).fill('Kesehatan')
  await page.evaluate(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function(key, value) {
      if (key.startsWith('dompet-santai-categories-v1:')) throw new DOMException('Full', 'QuotaExceededError')
      return original.call(this, key, value)
    }
  })
  await note.getByRole('button', { name: 'Simpan Kategori', exact: true }).click()
  await expect(note.locator('.category-error')).toContainText('belum tersimpan')
  await expect(note.getByLabel('Nama kategori', { exact: true })).toHaveValue('Kesehatan')
  await expect(note.getByRole('radio', { name: 'Kesehatan', exact: true })).toHaveCount(0)
  await note.getByRole('button', { name: 'Tutup tambah catatan' }).click()
  await expect(note.getByText('Isian belum disimpan. Tutup dan buang isian?')).toBeVisible()
  await note.getByRole('button', { name: 'Buang isian' }).click()
  await openNote(page)
  await expect(note.getByLabel('Nama kategori', { exact: true })).toHaveCount(0)
})


test('budget payment preference fills the wallet, allows overrides and can be edited or cleared', async ({ page }) => {
  test.setTimeout(60000)
  await signIn(page)
  await openBudgets(page)
  await page.getByRole('button', { name: 'Buat Anggaran', exact: true }).click()
  let editor = page.getByRole('dialog', { name: 'Buat Anggaran', exact: true })
  await expect(editor.getByLabel('Biasanya bayar dari (opsional)', { exact: true })).toHaveValue('')
  await expect(editor.getByLabel('Biasanya bayar dari (opsional)', { exact: true })).toContainText('6.500.000')
  await editor.getByLabel('Kategori', { exact: true }).selectOption('food')
  await editor.getByLabel('Batas anggaran (Rp)', { exact: true }).fill('1000000')
  await editor.getByLabel('Biasanya bayar dari (opsional)', { exact: true }).selectOption('cash')
  await editor.getByRole('button', { name: 'Simpan Anggaran' }).click()
  await expect(page.locator('.category-card')).toContainText('Biasanya: Tunai')
  await page.getByRole('button', { name: 'Lihat anggaran Makan & Minum' }).click()
  await page.getByRole('button', { name: 'Catat Pengeluaran', exact: true }).click()
  const note = page.getByRole('dialog', { name: 'Tambah Catatan' })
  await expect(note.getByLabel('Bayar dari', { exact: true })).toHaveValue('cash')
  await note.getByLabel('Nominal dalam rupiah').fill('450001')
  await expect(note.getByRole('button', { name: 'Simpan Catatan' })).toBeDisabled()
  await note.getByLabel('Nominal dalam rupiah').fill('30000')
  await note.getByLabel('Bayar dari', { exact: true }).selectOption('ewallet')
  await note.getByRole('button', { name: 'Simpan Catatan' }).click()
  await expect(page.locator('.detail-card')).toContainText('970.000')
  await expect(page.locator('.transactions li')).toContainText('E-Wallet')
  await page.getByRole('button', { name: 'Catat Pengeluaran', exact: true }).click()
  await expect(note.getByLabel('Bayar dari', { exact: true })).toHaveValue('cash')
  await expect(note.locator('#note-account option[value="cash"]')).toContainText('450.000')
  await expect(note.locator('#note-account option[value="ewallet"]')).toContainText('1.470.000')
  await note.getByRole('button', { name: 'Tutup tambah catatan' }).click()
  await note.getByRole('button', { name: 'Buang isian' }).click()
  await page.getByRole('button', { name: 'Ubah Anggaran', exact: true }).click()
  editor = page.getByRole('dialog', { name: 'Ubah Anggaran', exact: true })
  await expect(editor.getByLabel('Biasanya bayar dari (opsional)', { exact: true })).toHaveValue('cash')
  await editor.getByLabel('Biasanya bayar dari (opsional)', { exact: true }).selectOption('bank')
  await editor.getByRole('button', { name: 'Simpan Anggaran' }).click()
  await page.reload()
  await signIn(page)
  const next = await openNote(page)
  await next.getByRole('radio', { name: 'Makan & Minum', exact: true }).check()
  await expect(next.getByLabel('Bayar dari', { exact: true })).toHaveValue('bank')
  await next.getByLabel('Nominal dalam rupiah').fill('1000001')
  await expect(next.locator('.budget-warning')).toBeVisible()
  await expect(next.getByRole('button', { name: 'Simpan Catatan' })).toBeEnabled()
  await next.getByRole('button', { name: 'Tutup tambah catatan' }).click()
  await next.getByRole('button', { name: 'Buang isian' }).click()
  await openBudgets(page)
  await page.getByRole('button', { name: 'Lihat anggaran Makan & Minum' }).click()
  await page.getByRole('button', { name: 'Ubah Anggaran', exact: true }).click()
  await editor.getByLabel('Biasanya bayar dari (opsional)', { exact: true }).selectOption('')
  await editor.getByRole('button', { name: 'Simpan Anggaran' }).click()
  await expect(page.locator('.detail-card .wallet-preference')).toHaveCount(0)
  await page.getByRole('button', { name: 'Catat Pengeluaran', exact: true }).click()
  await expect(note.getByLabel('Bayar dari', { exact: true })).toHaveValue('ewallet')
})
test('budget payment preference follows category and date without overwriting a manual wallet choice', async ({ page }) => {
  await page.addInitScript(() => {
    const now = new Date()
    const month = now.getFullYear() + '-' + String(now.getMonth() + 1).padStart(2, '0')
    const key = 'dompet-santai-budgets-v1:00000000-0000-4000-8000-000000000123'
    if (!localStorage.getItem(key)) localStorage.setItem(key, JSON.stringify([
      { month, category: 'food', limit: 100000, defaultAccount: 'bank' },
      { month: '2020-01', category: 'food', limit: 100000, defaultAccount: 'ewallet' },
      { month, category: 'transport', limit: 100000 },
      { month, category: 'shopping', limit: 100000, defaultAccount: 'savings' },
    ]))
  })
  await signIn(page)
  const note = await openNote(page)
  await note.getByRole('radio', { name: 'Makan & Minum', exact: true }).check()
  await expect(note.getByLabel('Bayar dari', { exact: true })).toHaveValue('bank')
  const today = await note.getByLabel('Tanggal').inputValue()
  await note.getByLabel('Tanggal').fill('2020-01-02')
  await expect(note.getByLabel('Bayar dari', { exact: true })).toHaveValue('ewallet')
  await note.getByRole('radio', { name: 'Transportasi', exact: true }).check()
  await expect(note.getByLabel('Bayar dari', { exact: true })).toHaveValue('cash')
  await note.getByLabel('Tanggal').fill(today)
  await note.getByRole('radio', { name: 'Belanja', exact: true }).check()
  await expect(note.getByLabel('Bayar dari', { exact: true })).toHaveValue('cash')
  await expect(note.locator('#note-budget-account-help')).toContainText('belum tersedia')
  await note.getByRole('radio', { name: 'Makan & Minum', exact: true }).check()
  await expect(note.getByLabel('Bayar dari', { exact: true })).toHaveValue('bank')
  await note.getByRole('radio', { name: 'Pemasukan', exact: true }).check()
  await expect(note.getByLabel('Masuk ke', { exact: true })).toHaveValue('cash')
  await note.getByRole('radio', { name: 'Pengeluaran', exact: true }).check()
  await note.getByRole('radio', { name: 'Makan & Minum', exact: true }).check()
  await note.getByLabel('Bayar dari', { exact: true }).selectOption('cash')
  await note.getByLabel('Tanggal').fill('2020-01-02')
  await expect(note.getByLabel('Bayar dari', { exact: true })).toHaveValue('cash')
  await note.getByRole('radio', { name: 'Transportasi', exact: true }).check()
  await note.getByRole('radio', { name: 'Makan & Minum', exact: true }).check()
  await expect(note.getByLabel('Bayar dari', { exact: true })).toHaveValue('cash')
})

